# -*- coding: utf-8 -*-
{
    'name': 'J&T Express Integration',
    'summary': """J&T Express Integration will allow shippers to easily place, cancel, get quotes,
    and track orders via simple integration for delivery in Odoo.""",
    'author': 'Long Duong Nhat',
    'category': 'Inventory/Delivery',
    'support': 'odoo.tangerine@gmail.com',
    'version': '1.0.0',
    'depends': ['tangerine_delivery_base'],
    'data': [
        'security/ir.model.access.csv',
        'data/res_partner_data.xml',
        'data/delivery_jtexpress_data.xml',
        'data/jtexpress_route_api_data.xml',
        'data/jtexpress_status_data.xml',
        'data/jtexpress_status_mapping_data.xml',
        'data/ir_cron.xml',
        'wizard/choose_delivery_carrier_wizard_views.xml',
        'views/delivery_jtexpress_views.xml',
        'views/stock_picking_views.xml',
        'views/carrier_ref_order_views.xml',
    ],
    'post_init_hook': '_generate_master_data',
    'images': ['static/description/thumbnail.png'],
    'license': 'OPL-1',
    'installable': True,
    'auto_install': False,
    'application': True,
}
