# -*- coding: utf-8 -*-
{
    'name': '247 Express Integration',
    'summary': """247 Express Integration module will allow shippers to easily place, cancel, get quotes, and track orders via simple integration for delivery in Odoo.""",
    'author': 'Long Duong Nhat',
    'category': 'Inventory/Delivery',
    'support': 'odoo.tangerine@gmail.com',
    'version': '18.0.1.0',
    'depends': ['tangerine_delivery_base'],
    'data': [
        'security/ir.model.access.csv',
        'data/delivery_247_express_data.xml',
        'data/247_express_route_api_data.xml',
        'data/247_express_status_data.xml',
        'data/res_partner_data.xml',
        'data/ir_cron.xml',
        'wizard/choose_delivery_carrier_wizard_views.xml',
        'views/delivery_247_express_views.xml',
        'views/service_247_express_views.xml',
        'views/stock_picking_views.xml',
        'views/service_247_express_views.xml',
        'views/stock_warehouse_views.xml',
        'views/carrier_ref_order_views.xml'
    ],
    'images': ['static/description/thumbnail.png'],
    'license': 'OPL-1',
    'installable': True,
    'auto_install': False,
    'application': True,
}